services:
  bi:
    build: .
    ports:
      - 80:80
    depends_on:
      - postgres
    volumes:
      - ./logs/.log:/app/logs/.log
    environment:
      DSN: postgres://example:example@postgres:5432/embedded?sslmode=disable
      DB_TYPE: postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - ./migration:/docker-entrypoint-initdb.d

  example:
    image: metabase/metabase
    ports:
      - 3000:3000
